language: node_js
node_js:
  - 0.10

# Make sure we have new NPM.
before_install:
  - npm install -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - 'bower install'

after_script:
  - 'CODECLIMATE_REPO_TOKEN=183911307c7e62d8c7ff7aac1a0d20ca9e132bef0feedbcfe42a71d4e7b812e5 codeclimate < client/test/coverage/**/lcov.info'
