language: node_js
node_js:
  - 0.10

# Make sure we have new NPM.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - 'bower install'

after_script:
  - codeclimate < test/coverage/**/lcov.info

