language: node_js
node_js:
  - 0.10
before_install:
before_script:
  - npm install -g grunt-cli
  - npm install -d
  - npm install -g karma-coverage
branches:
  only:
    - master
after_success:
  - codeclimate < ./coverage/lcov.info
